/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.resourcebundle_example;

import java.util.Locale;
import java.util.ResourceBundle;

/**
 *
 * @author Alan.Ryan
 */
public class Main extends javax.swing.JFrame {
    
    //array to hold the options in the combobox
    String language[] = {"English", "French", "German", "Italian", "Spanish"};

    //array of locales
    Locale locales[] = {new Locale("en"), new Locale("fr"), new Locale("de"), new Locale("it"), new Locale("es")};

    //declare and create your resource bundle
    static ResourceBundle rb = ResourceBundle.getBundle("bundles.MyResourceBundle");

    //var to store the current/selected locale
    Locale locale;

    /**
     * Creates new form NewJFrame
     */
    public Main() {
        initComponents();
        
        setSize(400, 400);
        
         // Add locale names to the combo box
        for (String aLanguage : language) {
            localeCombo.addItem(aLanguage);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
     * Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        localeLabel = new javax.swing.JLabel();
        localeCombo = new javax.swing.JComboBox<>();
        nameLabel = new javax.swing.JLabel();
        nameJtf = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jobLabel = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(6, 2, 10, 10));

        localeLabel.setText("");
        getContentPane().add(localeLabel);

        localeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localeComboActionPerformed(evt);
            }
        });
        getContentPane().add(localeCombo);

        nameLabel.setText("");
        getContentPane().add(nameLabel);
        getContentPane().add(nameJtf);

        addressLabel.setText("");
        getContentPane().add(addressLabel);
        getContentPane().add(jTextField2);

        phoneLabel.setText("");
        getContentPane().add(phoneLabel);
        getContentPane().add(jTextField3);

        jobLabel.setText("");
        getContentPane().add(jobLabel);
        getContentPane().add(jTextField4);

        submitButton.setText("");
        getContentPane().add(submitButton);

        clearButton.setText("");
        getContentPane().add(clearButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void localeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localeComboActionPerformed
       //get the selected locale from the combobox
        locale = locales[localeCombo.getSelectedIndex()];

        //call the method updateStrings which will update all the GUI components to reflect the selection of a new locale
        updateStrings();
    }//GEN-LAST:event_localeComboActionPerformed

    private void updateStrings() {

        //load a new resource bundle based on the selection of a new locale
       rb = ResourceBundle.getBundle("bundles.MyResourceBundle", locale);

        //update all the labels, buttons and the title of the frame
        localeLabel.setText(rb.getString("Choose_Locale"));
        nameLabel.setText(rb.getString("Enter_Name"));
        addressLabel.setText(rb.getString("Enter_Address"));
        phoneLabel.setText(rb.getString("Enter_Phone"));
        jobLabel.setText(rb.getString("Enter_Job"));
        submitButton.setText(rb.getString("Submit_Button"));
        clearButton.setText(rb.getString("Clear_Button"));
        setTitle(rb.getString("Frame_Title"));

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel jobLabel;
    private javax.swing.JComboBox<String> localeCombo;
    private javax.swing.JLabel localeLabel;
    private javax.swing.JTextField nameJtf;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
